name: ARM Template Build and Test
on: [ push, pull_request ]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2    
    - name: Run Bicep build
      uses: aliencube/bicep-build-actions@v0.1
      with:
        files: '**/*.bicep'

    # Checks the result
    - name: Check the result
      shell: bash
      run: |
        shopt -s globstar
        ls -altR Bicep/*.*

    - name: Test Generated ARM Templates
      id: pathtest
      uses: aliencube/arm-ttk-actions@v0.3
      with:
        path: ./Bicep    

    - name: Test result - path
      shell: bash
      continue-on-error: true
      run: |
        echo "${{ toJSON(fromJSON(steps.pathtest.outputs.results)) }}"

    - name: Test ARM Templates
      id: pathtest2
      uses: aliencube/arm-ttk-actions@v0.3
      with:
        path: ./Arm-Templates    

    - name: Test arm - path
      shell: bash
      continue-on-error: true
      run: |
        echo "${{ toJSON(fromJSON(steps.pathtest2.outputs.results)) }}"

